# -*- coding: utf-8 -*-
"""KMeans_From_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZnRRdJPm9MyJJBYIiMy4dXZejJd6fVG
"""

!pip install numpy scikit-learn

import numpy as np


class KMeansFromScratch:
    def __init__(self, n_clusters=3, max_iters=300, tol=1e-4, random_state=None):
        self.n_clusters = n_clusters
        self.max_iters = max_iters
        self.tol = tol
        self.random_state = random_state

    def _initialize_centroids(self, X):
        np.random.seed(self.random_state)
        random_idx = np.random.choice(X.shape[0], self.n_clusters, replace=False)
        return X[random_idx]

    def _assign_clusters(self, X, centroids):
        distances = np.linalg.norm(X[:, np.newaxis] - centroids, axis=2)
        return np.argmin(distances, axis=1)

    def _update_centroids(self, X, labels):
        new_centroids = []
        for k in range(self.n_clusters):
            cluster_points = X[labels == k]
            if len(cluster_points) == 0:
                new_centroids.append(X[np.random.randint(0, X.shape[0])])
            else:
                new_centroids.append(cluster_points.mean(axis=0))
        return np.array(new_centroids)

    def _compute_inertia(self, X, centroids, labels):
        inertia = 0.0
        for k in range(self.n_clusters):
            cluster_points = X[labels == k]
            inertia += np.sum((cluster_points - centroids[k]) ** 2)
        return inertia

    def fit(self, X):
        self.centroids = self._initialize_centroids(X)

        for _ in range(self.max_iters):
            labels = self._assign_clusters(X, self.centroids)
            new_centroids = self._update_centroids(X, labels)

            if np.linalg.norm(new_centroids - self.centroids) < self.tol:
                break

            self.centroids = new_centroids

        self.labels_ = labels
        self.inertia_ = self._compute_inertia(X, self.centroids, labels)
        return self

import numpy as np
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


# Generate dataset
X, y = make_blobs(
    n_samples=500,
    centers=3,
    cluster_std=1.0,
    random_state=42
)

custom_inertias = []
custom_silhouettes = []

# Run custom K-Means 10 times
for seed in range(10):
    model = KMeansFromScratch(n_clusters=3, random_state=seed)
    model.fit(X)

    custom_inertias.append(model.inertia_)
    custom_silhouettes.append(
        silhouette_score(X, model.labels_)
    )

# Scikit-learn KMeans
sk_model = KMeans(n_clusters=3, n_init=10, random_state=42)
sk_labels = sk_model.fit_predict(X)

sk_inertia = sk_model.inertia_
sk_silhouette = silhouette_score(X, sk_labels)

print("===== Custom K-Means (From Scratch) =====")
print("Inertias (10 runs):", custom_inertias)
print("Average Inertia:", np.mean(custom_inertias))
print("Average Silhouette Score:", np.mean(custom_silhouettes))

print("\n===== Scikit-learn K-Means =====")
print("Inertia:", sk_inertia)
print("Silhouette Score:", sk_silhouette)

print("\n===== Stability Analysis =====")
print("Custom Inertia Variance:", np.var(custom_inertias))